sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: metafacture
    token: $SONARCLOUD_TOKEN
cache:
  directories:
    - $HOME/.sonar/cache

before_install:
  - ./travis/switch-to-branch.sh

script:
  - ./gradlew check
  - ./gradlew sonarqube

after_success:
  - ./travis/publish.sh
  - ./gradlew closeAndReleaseRepository

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file-glob: true
  file: ./metafacture-runner/build/distributions/metafacture-core-*
  skip-cleanup: true
  on:
    repo: culturegraph/metafacture-core
    tags: true
    condition: "$( git tag --list --format=\"%(objecttype)\" \"$TRAVIS_TAG\" ) == \"tag\""
