language: java
jdk:
  - openjdk6

env:
  global:
    - SONATYPE_USERNAME=culturegraph
    - secure:"IofaduUmiYcS340quETGzFcQkyLC+zYnn4FT4WuafMia7xW+WzM25XXkRauGU+J3xpW3w/2msCkXNdnlER3tl78nsE71X2etEIokHxBOhRYSZxD6JMiBAdDEdl4Qqkyws1huSJmzCZE3L/yP5P+BathKTf6jtjZqnC3KJZPl6U8="

after_success:
  - python travis-ci/configure-mvn.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml -Dgpg.skip=true -Psonatype-oss-release
