language: java
jdk:
  - openjdk6

env:
  global:
    - SONATYPE_USERNAME=culturegraph
    - secure:"LVLdZsSg17Y11G6ya7GYlApDPLHfpDAkXxOMDUQ8Q1F9WqiK6xt1IafdwQvyJc8KGDtnIofVSt5X1Fs87s4n+VuM6giRXolXI6nN2SpCVnpzmzhoaLXD04d36P6vOhadiTtdOKTjHuHn8fTMnhhKy2kUST+Uj1v8qSU2Ztma5nc="


after_success:
  - python travis-ci/configure-mvn.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml -Dgpg.skip=true -Psonatype-oss-release
